#!/bin/sh

# Want to accept the following user input
# 1) link to video
# 2) video or audio (if video best format)
# 3) if audio music or talk




# !!!!!!!! New instructions
# Provide a list of options 1-x ex: 1) Video only 2) Podcast 3) Music > assign result to a variable
# Next question: Move file to phone? (yn) > assign to variable
# Proceed through and since result is in variable, nesting should be unnecessary

# To see if phone is connected: phone_connected=`find -n mtpwhatever`
# To get output length size=${#phone_connected}; echo $size

# ------------------------------------------------------------------------------------------------

# Float window and send (hide) success message to /dev/null
i3-msg floating enable > /dev/null

read -p "Enter the video's url: " url

while true; do
	read -p "Make a selection:
		1) Video only	
		2) Audio only - Podcast/Talkshow
		3) Audio only - Music
	" selection 
	case $selection in
		[1]* ) 
			cd ~/Videos; 
			i3-msg move scratchpad;
			youtube-dl $url; 
			notify-send --icon=gtk-info -t 5000 youtube-dl "Completed download of $url"
			exit;;
		[2]* ) 

			cd ~/Music/Talk; 
			i3-msg move scratchpad;
			youtube-dl -x --audio-format mp3 $url;
			notify-send --icon=gtk-info -t 5000 youtube-dl "Completed download of $url"
			exit;;
		[3]* ) 
			cd ~/Music; 
			i3-msg move scratchpad;
			youtube-dl -x --audio-format mp3 $url;
			notify-send --icon=gtk-info -t 5000 youtube-dl "Completed download of $url"
			exit;;
		* ) echo "Please make a valid selection.";;
	esac
done
