#!/bin/sh

# This script is a wrapper for youtube-dl that provides a convenient prompt for different options.

# ------------------------------------------------------------------------------------------------

# Float window and send (hide) success message to /dev/null
i3-msg floating enable > /dev/null

read -p "Enter the video's url: " url

while true; do

	# Present download options
	read -p "Make a selection:
		1) Video only	
		2) Audio only - Podcast/Talkshow
		3) Audio only - Music
	" selection 

	# Process selection
	case $selection in
		[1]* ) 
			cd ~/Videos; 
			i3-msg move scratchpad;
			youtube-dl $url; 
			notify-send --icon=gtk-info -t 5000 youtube-dl "Completed download of $url"
			break;;
		[2]* ) 

			cd ~/Music/Talk; 
			i3-msg move scratchpad;
			youtube-dl -x --audio-format mp3 $url;
			notify-send --icon=gtk-info -t 5000 youtube-dl "Completed download of $url"
			break;;
		[3]* ) 
			cd ~/Music; 
			i3-msg move scratchpad;
			youtube-dl -x --audio-format mp3 $url;
			notify-send --icon=gtk-info -t 5000 youtube-dl "Completed download of $url"
			break;;
		* ) echo "Please make a valid selection.";;
	esac
		
done
