#!/bin/sh

# Want to accept the following user input
# 1) link to video
# 2) video or audio (if video best format)
# 3) if audio music or talk

# Float window and send (hide) success message to /dev/null
i3-msg floating enable > /dev/null

read -p "Enter the video's url: " url
echo "The url is: $url!"

while true; do
	read -p "Download audio only? " yn
	case $yn in
		[Yy]* ) 
			while true; do
				read -p "Is this an audio book, talkshow, or podcast? " yn
				case $yn in
					[Yy]* ) 
						cd ~/Music/Talk; 
						i3-msg move scratchpad;
						youtube-dl -x --audio-format mp3 $url;
						notify-send --icon=gtk-info -t 5000 youtube-dl "Completed download of $url"
						break;;
					[Nn]* ) 
						cd ~/Music; 
						i3-msg move scratchpad;
						youtube-dl -x --audio-format mp3 $url;
						notify-send --icon=gtk-info -t 5000 youtube-dl "Completed download of $url"
						exit;;
					* ) echo "Please answer yes or no.";;
				esac
			done
			break;;
		[Nn]* ) 
			cd ~/Videos; 
			i3-msg move scratchpad;
			youtube-dl $url; 
			notify-send --icon=gtk-info -t 5000 youtube-dl "Completed download of $url"
			exit;;
		* ) echo "Please answer yes or no.";;
	esac
done
